[package]
name = "pumpkin-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-config = { path = "../pumpkin-config" }
pumpkin-macros = { path = "../pumpkin-macros" }
pumpkin-world = { path = "../pumpkin-world" }
pumpkin-core = { path = "../pumpkin-core" }

bytes = "1.7"

uuid.workspace = true

serde.workspace = true

flate2 = "1.0"

thiserror = "1.0"
log.workspace = true
num-traits = "0.2"
num-derive = "0.4"

# encryption
aes = "0.8.4"
cfb8 = "0.8.1"

itertools.workspace = true
fastnbt = { git = "https://github.com/owengage/fastnbt.git" }

futures = "0.3.30"
pin-project-lite = "0.2.14"
tokio.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true
