[package]
name = "pumpkin-registry"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-protocol = { path = "../pumpkin-protocol"}
pumpkin-core = { path = "../pumpkin-core"}

# nbt
fastnbt = { git = "https://github.com/owengage/fastnbt.git" }

serde.workspace = true
