[package]
name = "pumpkin-world"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-core = { path = "../pumpkin-core" }
pumpkin-macros = { path = "../pumpkin-macros" }

fastnbt = { git = "https://github.com/owengage/fastnbt.git" }
tokio.workspace = true
rayon.workspace = true
derive_more.workspace = true
itertools.workspace = true
thiserror = "1.0"
futures = "0.3"


# Compression
flate2 = "1.0"
lz4 = "1.11.1"

serde.workspace = true
serde_json = "1.0"
enum_dispatch = "0.3.13"
derive-getters = "0.5.0"

log.workspace = true

parking_lot.workspace = true

noise = "0.9.0"

rand = "0.8.5"

num-traits = "0.2"
num-derive = "0.4"
