[package]
name = "pumpkin-world"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-core = { path = "../pumpkin-core"}

fastnbt = { git = "https://github.com/owengage/fastnbt.git" }
tokio.workspace = true
rayon.workspace = true
derive_more.workspace = true
itertools = "0.13.0"
thiserror = "1.0"
futures = "0.3"
flate2 = "1.0"
serde.workspace = true
serde_json = "1.0"
static_assertions = "1.1.0"
log.workspace = true

noise = "0.9.0"

rand = "0.8.5"

num-traits = "0.2"
num-derive = "0.4"
