[package]
name = "pumpkin-core"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-nbt = { path = "../pumpkin-nbt" }
serde.workspace = true
bytes.workspace = true
uuid.workspace = true

num-traits = "0.2"

colored = "2"
md5 = "0.7.0"
