[package]
name = "pumpkin-config"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-core = { path = "../pumpkin-core" }
serde.workspace = true
log.workspace = true

toml = "0.8"
